### ISSUE TITLE
мда

### ISSUE THREAD

**Issue by hissssst** [n30np14gu3/secretmoney#1]
Вроде взрослые люди, а какой мелкий скам

**Comment by n30np14gu3** [comment]
Это заказ был. Меня в целом не волновало, что с проектом будет дальше. Да и судя по логам в БД ничего у челов не выгорело

**Comment by hissssst** [comment]
Марку и Андрею привет :3

**Comment by n30np14gu3** [comment]
Да я сам с Марком не против бы встретиться. Так сказать надо бы долг забрать.
